### ISSUE TITLE
Different storage support for different modules

### ISSUE THREAD

**Issue by ArtemZip** [Thomaash/vuex-ltm#1459]
I see currently it's possible to reduce persistence to one module, but what if I want to store one module into sync storage and another module to a local storage, how can I do it?

**Comment by Thomaash** [comment]
Hi @ArtemZip, you can simply create multiple instances of the plugin, one instance for the module stored in sync storage and another instance for the module in local storage. As long as you don't try to touch the same data from both instances, there should be absolutely no problems at all.
